### ISSUE TITLE
Promise: data_get() and cancel with dead_promise pointer

### ISSUE THREAD

**Issue by barbieri** [profusion/efl#13]
In many cases people will pass the "promise to be resolved" to callbacks. Since the promise stores the data for cancel, then allow to retrieve it:

```c
EAPI void *eina_promise_data_get(const Eina_Promise *p) EINA_ARG_NONNULL(1); // also validate promise!
```

Last but not least, since users may have stored this `promise`, provide the dead pointer in cancel... this is used when the cancel is called by `eina_future_cancel()`:

```c
typedef void (Eina_Promise_Cancel_Cb)(void *data, const Eina_Promise *dead_promise);
```

**Comment by cabelitos** [comment]
done
